### ISSUE TITLE
Zu selten genannte Begriffe

### ISSUE THREAD

**Issue by fin-ger** [AreonDev/BanaBINGO#2]
Ich schlage das entfernen folgender Begriffe aus der Liste vor:

* [ ] Aber Go ist schnell. - Und Einfach. - Einfach schnell.
* [ ] Hallo OpenRC Paul.
* [ ] Rootrot
* [ ] Puddingscience
* [ ] Pöbelheinz

> Bitte nicht hier anhaken, sondern als comment abgeben

**Comment by fia0** [comment]
Hallo ... +1
Pöbelheinz +1

**Comment by martin31821** [comment]
![Senf](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Senf-3.jpg/220px-Senf-3.jpg)

**Comment by fin-ger** [comment]
@martin31821 Danke, dass du deinen Senf abgibst

**Comment by fin-ger** [comment]
Rootrot +1
Hallo ... +1
Pöbelheinz +1

**Comment by fin-ger** [comment]
EOL
