### ISSUE TITLE
Generalisierung einiger Begriffe

### ISSUE THREAD

**Issue by fin-ger** [AreonDev/BanaBINGO#3]
Ich schlage das generalisieren folgender Einträge vor:

Kannste schon so machen, ist dann halt kacke. -> Kannste schon so machen, ist dann halt ...

Na gut kannste weglassen, funktioniert dann halt nicht. -> ... funktioniert dann halt nicht.

**Comment by fia0** [comment]
+1

**Comment by wfailla** [comment]
+1

**Comment by fin-ger** [comment]
EOL
