### ISSUE TITLE
Matchmaking

### ISSUE THREAD

**Issue by fin-ger** [AreonDev/BanaBINGO#4]
Matchmaking mit einer Custom Karte pro Spieler und announcen eines Gewinners.

**Comment by martin31821** [comment]
Bei allen Verlierern sollte dann groß ein Schriftzug eingeblendet werden (mit Animation) und ein Sound abgespielt werden...

**Comment by greaka** [comment]
dann braucht man aber nen anti cheat...

**Comment by fin-ger** [comment]
EOL
